enum ACTION_TYPES {
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  SIGNUP = 'SIGNUP',
  REQUEST_PASSWORD_RESET = 'REQUEST_PASSWORD_RESET',
  RESET_PASSWORD = 'RESET_PASSWORD',
  REQUEST_ACCOUNT_VERIFICATION = 'REQUEST_ACCOUNT_VERIFICATION',
  VERIFY_ACCOUNT = 'VERIFY_ACCOUNT',
  PLAY = 'PLAY',
  ADD_TO_PLAY_QUEUE = 'ADD_TO_PLAY_QUEUE',
  FILL_PLAY_QUEUE = 'FILL_PLAY_QUEUE',
  PAUSE = 'PAUSE',
  STOP = 'STOP',
  SKIP_FORWARD = 'SKIP_FORWARD',
  SKIP_BACK = 'SKIP_BACK',
  CHANGE_REPEAT = 'CHANGE_REPEAT',
  CHANGE_SHUFFLE = 'CHANGE_SHUFFLE',
  SETUP_PLAYER = 'SETUP_PLAYER',
}

export {
  ACTION_TYPES,
}
