enum COMMIT_TYPES {
  AUTHENTICATED = 'AUTHENTICATED',
  UNAUTHENTICATED = 'UNAUTHENTICATED',
  CHANGE_APP_WAITING = 'CHANGE_APP_WAITING',
  CHANGE_REPEAT = 'CHANGE_REPEAT',
  CHANGE_SHUFFLE = 'CHANGE_SHUFFLE',
  PLAYING = 'PLAYING',
  PAUSED = 'PAUSED',
  STOPPED = 'STOPPED',
  APP_WAITING = 'APP_WAITING',
}

export {
  COMMIT_TYPES,
}
