enum COMMIT_TYPES {
  AUTHENTICATED = 'AUTHENTICATED',
  UNAUTHENTICATED = 'UNAUTHENTICATED',
  CHANGE_APP_WAITING = 'CHANGE_APP_WAITING',
  CHANGE_REPEAT = 'CHANGE_REPEAT',
  CHANGE_SHUFFLE = 'CHANGE_SHUFFLE',
  PLAYING = 'PLAYING',
  SEEK = 'SEEK',
  TOTAL_DURATION = 'CURRENT_DURATION',
  PAUSED = 'PAUSED',
  STOPPED = 'STOPPED',
  APP_WAITING = 'APP_WAITING',
  HOME_SCREEN_TAB_INDEX = 'HOME_SCREEN_TAB_INDEX',
}

export {
  COMMIT_TYPES,
}
